
# *************************************************************
#
# The OpenTRV project licenses this file to you
# under the Apache Licence, Version 2.0 (the "Licence");
# you may not use this file except in compliance
# with the Licence. You may obtain a copy of the Licence at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the Licence is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the Licence for the
# specific language governing permissions and limitations
# under the Licence.
#
# *************************************************************
# Author(s) / Copyright (s): Mark Hill 2017
#                            Deniz Erbilgin 2017
#                            Damon Hart-Davis 2017

dist: trusty
sudo: required
group: edge
language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
before_install:
 - $CXX --version
 - clang++ --version
 - sudo apt-get -qq update
 - sudo apt-get install -y libgtest-dev
 - wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
 - tar xf release-1.7.0.tar.gz
 - cd googletest-release-1.7.0
# - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - cd make
 - make
# - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
 - sudo cp -a gtest_main.a /usr/lib/libgtest_main.a
 - sudo cp -a gtest_main.a /usr/lib/libgtest.a
 - cd ..
 - sudo cp -a include/gtest /usr/include
 - cd "${TRAVIS_BUILD_DIR}"
 - chmod +x PortableUnitTestsDriver.sh
# Setup Arduino IDE
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16 -extension RANDR"
 - sleep 3
 - export DISPLAY=:1.0
 - wget http://downloads.arduino.cc/arduino-1.8.1-linux64.tar.xz
 - tar xf arduino-1.8.1-linux64.tar.xz
 - sudo mv arduino-1.8.1 /usr/local/share/arduino
 - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
 - arduino --pref "boardsmanager.additional.urls=https://raw.githubusercontent.com/opentrv/OpenTRV-Config/master/Arduino/package_opentrv_index.json" --save-prefs
 - arduino --install-boards "opentrv:avr"
 - arduino --pref "boardsmanager.additional.urls=" --save-prefs
 - ls -al
 - ln -s $PWD/OTAESGCM/content/OTAESGCM /usr/local/share/arduino/libraries/OTAESGCM
script: ./PortableUnitTestsDriver.sh
notifications:
  email:
    recipients:
      - ci@opentrv.uk
    on_success: change
    on_failure: always
  irc:
    channels: "irc.z.je#opentrv"
    on_success: change
    on_failure: change
  

